enable: true

message: true
launch-message: '&9Joepie!!!'

#CHANGE THIS TO WHATEVER YOU WANT
#FULL MATERIAL LIST HERE: https://hub.spigotmc.org/javadocs/bukkit/org/bukkit/Material.html
top-block: 'SLIME_BLOCK'
bottom-block: 'REDSTONE_BLOCK'

y-velocity: 2 #change this to how high you want to go
velocity-multiplier: 3 #change this to how fast you want to go

disable-fall-damage: true